package pokemon;

/**
 * 
 * @author Kai
 *
 * hier sind alle Erlernbaren Attackennamen gespeichert 
 */
public enum AttackenNamen {
	RUCKZUCKHIEB, DONNERSCHOCK, DONNER, TACKLE, FUNKENSPRUNG,  FLAMMENWURF, GLUT, 
	PLATSCHER, RUTENSCHLAG, DONNERBLITZ, BODYSLAM, FLAMMENBLITZ, HITZEWELLE, KRATZER, FLUEGELSCHLAG, 
	GRIMASSE, FEUERZAHN, FUNKENFLUG, SCHLITZER, INFERNO,
	HEULER, ELEKTROBALL, SLAM, OFFENLEGUNG, LADUNGSSTOSS,
	RANKENHIEB, BODYCHECK, RASIERBLATT, LOCKDUFT, RISIKOTACKLE, SAMENBOMBEN, SOLARSTRAHL, BLUETENWIRBEL,
	AQUAKNARRE, BLUBBER, DRESCHFLEGEL, HYPERSTRAHL, SILBERBLICK, FUCHTLER,
	
	WINDSTOSS, WIRBELWIND, RUECKENWIND, LUFTSCHNITT, ORKAN,
	ENERGIEFOKUS, HYPERZAHN, SUPERZAHN, 
	SCHNABEL, AERO_ASS, BOHRSCHNABEL,
	PFUND, SAEUSELSTIMME, DUPLEXHIEB, EINIGLER, WECKRUF, KRAFTVORRAT, KOSMIKKRAFT, STERNSCHAUER,
	SONDERSENSOR,
	ABSORBER, MEGASAUGER, BEERENKRAEFTE, GIGASAUGER, BLAETTERTANZ,
	MOGELHIEB, KRATZFURIE, 
	KONFUSION,
	PSYCHOKLINGE, PSYCHOKINESE, PSYSTRAHL, 
	KOPFNUSS, ZEN_KOPFSTOSS, 
	BLITZKANONE,
	STURZFLUG,
	KLAMMER, BLUBBSTRAHL, STAMPFER, GUILLOTINE, KRABBHAMMER,
	KUGELSAAT,
	ZERMUERBEN, BLATTGEISSEL,
	EIERBOMBE,
	DONNERSCHLAG, FEUERSCHLAG,
	FLAMMENSTURM, FEUERSTURM,
	BAUCHTROMMEL, GIGASTOSS,
	PSYCHOSTOSS
}
