package pokemon;

public enum AttackenNamen {
	RUCKZUCKHIEB, DONNERSCHOCK, DONNER, TACKLE, FUNKENSPRUNG, AQUAKNARRE, FLAMMENWURF, GLUT, 
	BLUBBER, RANKENHIEB, BLÄTTERTANZ, PFUND, PLATSCHER, RUTENSCHLAG, DONNERBLITZ, BODYSLAM
}
