package pokemon;

/**
 * 
 * @author Kai
 *
 *	Pokemon die im Spiel auftauchen können
 */
public enum PokeNamen {
	BISASAM, BISAKNOSP, BISAFLOR, GLUMANDA, GLUTEXO, GLURAK, SCHIGGY, SCHILLOK, TURTOK, PIKACHU, RAICHU, KARPADOR, GARADOS,
	TAUBSI, TAUBOGA, TAUBOSS, RATTFRATZ, RATTIKARL, HABITAK, IBITAK, PIEPI, PIXI, VULPIX, VULNONA,	
	MYRAPLA, DUFLOR, GIFLOR, MAUZI, SNOBILIKAT, ENTON, ENTORON, FUKANO, ARKANI,	ABRA, KADABRA, SIMSALA, 	
	FLEGMON, LAHMUS, MAGNETILO, MAGNETON, PORENTA, TRAUMATO, HYPNO, KRABBY, KINGLER, 
	OWEI,	KOKOWEI, SCHLURP, CHANEIRA, TANGELA, STERNDU, STARMIE, PANTIMOS, ELEKTEK, MAGMAR, RELAXO, RAUPY, HORNLIU, ONIX, KLEINSTEIN,	
	
	ARKTOS, ZAPDOS, LAVADOS, MEWTU
}
